"""Added Models

Revision ID: 072461156a77
Revises: cad6feaa36b4
Create Date: 2023-12-18 08:22:00.891767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072461156a77'
down_revision = 'cad6feaa36b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
